version: 2
jobs:
  build:
    working_directory: ~/verified-library
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - store_artifacts:
          path: ./dist
      - deploy:
          name: CDN
          ##- aws s3 sync ./dist s3://circle-production-static-site/docs/ --delete
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            export PATH=~/.local/bin:$PATH
            pip install awscli --upgrade --user
            aws s3 cp ./dist/ s3://verified-cdn --recursive --acl public-read


